version: '2'

services: 
    caddy:
        image: caddy:2
        container_name: caddy
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./arrakis-ingress/out:/var/www/
            - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
        restart: unless-stopped
        network_mode: "host"
        environment:
            - TS_PERMIT_CERT_UID=caddy
