version: '2'

services: 
    caddy:
        image: caddy:2
        container_name: caddy
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./index.html:/var/www/index.html
        restart: unless-stopped
        environment:
            - TS_PERMIT_CERT_UID=caddy
